baseUrl: "https://lqhl.github.io/"
title: "Qin's Blog"
author: "Qin Liu"
languageCode: "zh-Hans"
theme: ezhil
enableRobotsTXT: true

params:
  title: "Qin's Blog"

menu:
  main:
  - {name: "Home", url: "/", identifier: "home", weight: 1}
  - {name: "Post", url: "/post/", identifier: "post", weight: 3}
  - {name: "Tag", url: "/tags/", identifier: "tag", weight: 4}
  - {name: "RSS", url: "/index.xml", identifier: "rss", weight: 5}
  - {name: "About", url: "/about/", identifier: "address-card", weight: 10}

permalinks:
  post: "/post/:slug/"
  page: "/:slug/"

taxonomies:
  category: categories
  tag: tags

# Enable syntax highlighting.
pygmentsstyle: "solarized-dark"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

# Your Google analytics code.
# googleAnalytics: "UA-123-45"
# Your Disqus sortname.
disqusShortname: "lqhl"


# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate: 10

# Number of characters to show in summary.
summaryLength: 20

params:
  # Blog subtitle which appears below blog title. Supports markdown.
  subtitle: "Blog by [Qin Liu](https://lqhl.me)"

  # Content types which are included in home page recent posts list.
  mainSections: ["post"]

  # Content types which are excludes Disqus comments.
  disableDisqusTypes: ["page"]

  # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
  featherIconsCDN: true

  # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
  # favicon: "icons/myicon.png"

  # Switch to dark mode or auto detect mode from OS (Optional).
  # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
  mode: "dark" # "dark" or "auto"

  # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
  # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
  # you can specify custom css path as `css/custom.css`.
  # customCSS: "css/custom.css"
  # Custom CSS added to dark mode style.
  # customDarkCSS: "css/custom-dark.css"

  # Custom list of Javascript files to load. Just like custom CSS you can place js files under
  # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
  # for example you may want to include external JS library.
  # customJS: ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]

  social:
    - {name: "GitHub", url: "https://github.com/lqhl", icon: "github"}
    - {name: "Twitter", url: "https://twitter.com/lqhl", icon: "twitter"}

