baseURL = "https://lqhl.github.io/"
languageCode = "zh-Hans"
title = "Qin's Blog"
theme = "tale"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/post/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 0

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 0

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
