baseUrl: "https://lqhl.github.io/"
theme: hugo-bearblog

publishDir: docs

title: "巴别之塔"
author: "lqhl"
copyright: "Copyright © 2021, lqhl."
languageCode: zh

# Generate a nice robots.txt for SEO
enableRobotsTXT: true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds:
  - "taxonomy"
ignoreErrors:
  - "error-disable-taxonomy"
permalinks:
  blog: "/:slug/"
  tags: "/blog/:slug"

# Your Disqus sortname.
disqusShortname: "lqhl"

params:
  title: "巴别之塔"
  description: "九百六十万平方公里土地，五千年文明，十三亿人口……如果要建一座通天塔的话，再没有比这里更理想的地基了……"

markup:
  highlight:
    style: github
